apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: demo-project
  source:
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: 'master'
    path: guestbook
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  info:
  - name: 'Guestbook'
    value: 'Application demo'
